name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  frontend:
    name: Frontend tests
    if: ${{ !contains(github.event.head_commit.message, '#skip') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies for frontend
        run: cd frontend && npm install
      - name: Lint frontend
        run: cd frontend && npm run lint
  deploy:
    name: Backend tests and deploy app
    if: ${{ !contains(github.event.head_commit.message, '#skip') }}
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: install dependencies for backend
        run: cd backend && npm install
      - name: run backend lint
        run: cd backend && npm run lint
      - name: deploy to Fly
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
